### ISSUE TITLE
AMC image request

### ISSUE THREAD

**Issue by hryamzik** [aerospike/aerospike-server.docker#22]
AMC is very useful and it would be great to have it in registry as well.

Dockerfile:
```
FROM ubuntu:xenial

ENV AMC_VERSION 3.6.13
ENV AMC_SHA256 f55f5ef3108e7da7c112fb12ceb1dca017e567c6ba1d311f604948ae347da3f0

RUN \
  apt-get update -y \
  && apt-get install -y wget python-dev gcc \
  && wget "http://www.aerospike.com/artifacts/aerospike-amc-community/${AMC_VERSION}/aerospike-amc-community-${AMC_VERSION}.all.x86_64.deb" -O aerospike-amc.deb \
  && echo "$AMC_SHA256 aerospike-amc.deb" | sha256sum -c - \
  && dpkg -i aerospike-amc.deb \
  && rm -rvf aerospike-amc.deb \
  && dpkg -r wget ca-certificates \
  && dpkg --purge wget ca-certificates \
  && apt-get purge -y

EXPOSE 8081

CMD ["/opt/amc/bin/gunicorn", "--config=/etc/amc/config/gunicorn_config.py", "flaskapp:app"]
```

docker-compose.yml:
```yml
version: '2'
services:
  aerospike:
    restart: always
    container_name: aerospike
    image: aerospike/aerospike-server
    ports:
      - 3000:3000
      - 3001:3001 
      - 3002:3002
      - 3003:3003
    volumes:
      - $PWD/etc/aerospike.conf:/etc/aerospike/aerospike.conf
  
  amc:
    restart: always
    build: ./
    ports:
      - 8081:8081
    container_name: amc
    links:
          - aerospike
```
